export const iconsClassBootsrap = {
  arrowRight: "bi bi-arrow-right-short",
  addImg: "bi-file-earmark-image",
  file: "bi bi-file-earmark-medical",
  favourite: "bi bi-heart",
  mute: "bi bi-bell-slash",
  block: "bi bi-ban",
  camera: "bi bi-camera-video-fill",
  contact: "bi bi-person-lines-fill",
  chat: "bi bi-wechat",
  delete: "bi bi-trash",
  edit: "bi bi-pencil",
  addUser: "bi bi-person-plus",
  userFill: "bi bi-person-fill",
  users: "bi bi-people-fill",
  micFill: "bi bi-mic-fill",
  phoneFill: "bi bi-telephone-fill",
  phoneOutline: "bi bi-telephone",
  info: "bi bi-info",
  settings: "bi bi-gear",
  signOut: "bi bi-box-arrow-right",
  send: "bi bi-send",
  moreHorizontally: "bi bi-three-dots",
  moreVertically: "bi bi-three-dots-vertical",
  download: "bi bi-cloud-download",
  share: "bi bi-share",
  reply: "bi bi-reply",
  checked: "bi bi-check2",
};
